version: "3.3"

services:
  traefik:
    image: "traefik"
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/containers/traefik/data/acme.json:/acme.json"
      - "/opt/containers/traefik/data/traefik.yml:/traefik.yml:ro"
      - "/opt/containers/traefik/data/config.yml:/config.yml:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.spaceling.sh`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users="
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.spaceling.sh`)
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.tls.domains[0].main=spaceling.sh"
      - "traefik.http.routers.traefik.tls.domains[0].sans=*.spaceling.sh"
      - "traefik.http.routers.traefik.service=api@internal"
    environment:
      - CF_API_EMAIL=webmaster@spaceling.sh
      - CF_API_KEY=

  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/containers/calibre-web/config:/config"
      - "/opt/containers/calibre-web/books:/books"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.entrypoints=http"
      - "traefik.http.routers.calibre.rule=Host(`calibre.spaceling.sh`)"
      - "traefik.http.routers.calibre.middlewares=https-redirect@file"
      - "traefik.http.routers.calibre-secure.middlewares=secured@file"
      - "traefik.http.routers.calibre-secure.entrypoints=https"
      - "traefik.http.routers.calibre-secure.rule=Host(`calibre.spaceling.sh`)"
      - "traefik.http.routers.calibre-secure.tls=true"
      - "traefik.http.routers.calibre-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.calibre-secure.service=calibre"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"
      - "traefik.docker.network=proxy"
    environment:
      - "PUID=1001"
      - "PGID=1001"


  syncthing:
    image: linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/containers/syncthing/config:/config"
      - "/opt/containers/syncthing/data:/data"
      - "/opt/containers/calibre-web/books:/books"
    ports:
      - "8384:8384"
      - "22000:22000"
      - "21027:21027/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.entrypoints=http"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.spaceling.sh`)"
      - "traefik.http.routers.syncthing.middlewares=https-redirect@file"
      - "traefik.http.routers.syncthing-secure.middlewares=secured@file"
      - "traefik.http.routers.syncthing-secure.entrypoints=https"
      - "traefik.http.routers.syncthing-secure.rule=Host(`syncthing.spaceling.sh`)"
      - "traefik.http.routers.syncthing-secure.tls=true"
      - "traefik.http.routers.syncthing-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.syncthing-secure.service=syncthing"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "traefik.docker.network=proxy"
    environment:
      - "PUID=1001"
      - "GUID=1001"
      - "UMASK_SET=<022>"

  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      CONTAINERS: 1

  networks:
    proxy:
      external: true