version: "3.8"
##################
# VPNS - // - docker@vps side
##################

##################
# Services
##################
services:
# SWAG - // - LSIO Secure Web Application Gateway
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - URL=$DOMAIN
      - EXTRA_DOMAINS=*.$DOMAIN
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./swag/config:/config
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    restart: unless-stopped

# Wireguard - // - an extremely simple yet fast and modern VPN
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - SERVERURL=$DOMAIN
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=$WG_SUBNET
      - ALLOWEDIPS=$WG_IPS
    volumes:
      - ./wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 80:80
      - 443:443
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
