version: "3.8"

##################
# VPND - // - Docker@home side
##################

services:
##################
# SWAG - // - LSIO Secure Web Application Gateway
##################
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - URL=$DOMAIN
      - EXTRA_DOMAINS=*.$DOMAIN
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./swag/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

##################
# Wireguard - // - an extremely simple yet fast and modern VPN
##################
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - ./Wireguard/config:/config
      - /lib/modules:/lib/modules
    restart: unless-stopped
